### ISSUE TITLE
export_json is deprecated? error

### ISSUE THREAD

**Issue by prituladima** [SOM-Research/busfactor#3]
I can't find export_json in Gitana project. I tried another methods. 
Even checked out tag/0.2 but no results.
Only think I could do is to put project to db. 
But  have another error when trying save it to json.
File "db2json_gui.py", line 241, in execute_export
    g.db2json(self.DBNAME, self.OUTPUT_JSON, self.LINE_DETAILS)
  File "/Gitana/gitana.py", line 39, in db2json
    exporter.export()
  File "/Gitana/db2json.py", line 420, in export
    self.set_repo_id()
  File "/Gitana/db2json.py", line 30, in set_repo_id
    self.repo_id = row[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
 I think it's no problem than to generate report from json. But I still have no idea what to do with this

**Comment by Namingwaysway** [comment]
I'm getting the same error, it seems that it's also missing from the Gitana repo.

**Comment by jlcanovas** [comment]
Hi @Namingwaysway, that's right, the evolution of [Gitana](https://github.com/SOM-Research/Gitana) broke this feature. 

For the moment we don't have an immediate plan to address this but if you give it a try, any help is welcome.

**Comment by ubaierbhat** [comment]
Use @valeriocos's fork of Gitana https://github.com/valeriocos/Gitana
